artist_dashboard/urls.py
from django.urls import path, include

from artist_dashboard.views import artist_dashboard, update_profile, artworks, edit_artwork, orders, reviews, account_details, delete_artwork, order_detail, offers, offer_detail

app_name = "artist-dashboard"


urlpatterns = [
    path("", artist_dashboard, name="artist-dashboard"),
    path("update-profile/<aid>/", update_profile, name= "update-profile"),
    path("artworks/", artworks, name="artworks"),
    path("edit-artwork/<pid>/", edit_artwork, name="edit-artwork"),
    path("delete-artwork/<pid>/", delete_artwork, name = "delete-artwork"),
    path("orders/", orders, name="orders"),
    path("orders/order-details/<id>", order_detail, name = "order-details"),
    path("reviews/", reviews, name="reviews"),
    path("account-details/", account_details, name="account-details"),
    path("offers/", offers, name="offers"),
    path("offers/offer-details/<id>", offer_detail, name = "offer-details"),

]

atlas/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path("user/",include("userauths.urls")),
    path("artist-dashboard/", include("artist_dashboard.urls")),

    # google authentication and whatnot
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home.views import index, product_list_view, artist_list_view, artist_detail_view, product_detail_view, add_product_review, add_artist_review, artist_search_view, product_search_view, add_to_cart, cart_view, delete_item_from_cart, payment, payment_completed_view, payment_failed_view, customer_dashboard, order_details, update_address_status, delete_address, wishlist_view, add_to_wishlist, delete_item_from_wishlist, services_view, contact_view, about_view, faqs_view, checkout, update_order, make_offer

app_name = "home"

urlpatterns = [
    path("",index, name="index"),
    path("services/", services_view, name = "services"),
    path("contact/", contact_view, name = "contact"),
    path("about/", about_view, name = "about"),
    path("faqs/", faqs_view, name = "faqs"),

    path("store/",product_list_view, name="store"),
    path("store/<pid>/",product_detail_view, name="product-details"),

    path("artists/", artist_list_view, name = "artists"),
    path("artists/<aid>/",artist_detail_view, name="artist-details"),

    path("add-product-review/<int:pid>/",add_product_review, name ="add-product-review"),
    path("add-artist-review/<int:aid>/",add_artist_review, name ="add-artist-review"),

    path("search/artists/", artist_search_view, name = "artist-search"),
    path("search/artworks/", product_search_view, name= "product-search"),

    path("add-to-cart/", add_to_cart, name = "add-to-cart"),
    path("cart/",cart_view, name="cart"),
    path("delete-from-cart/",delete_item_from_cart, name="delete-from-cart"),

    path("payment/<oid>/", payment, name ="payment"),

    path("checkout/", checkout, name = "checkout"),

    path("paypal/", include('paypal.standard.ipn.urls')), 
    path("payment/payment-completed/<oid>/", payment_completed_view, name = "payment-completed"),
    path("payment/payment-failed/", payment_failed_view, name = "payment-failed"),
    path("update-order/", update_order, name = "update_order"),

    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_details, name="order-details"),
    path("update-address-status/", update_address_status, name = "update-address-status"),
    path("delete-address/", delete_address, name = "delete-address"),

    path("wishlist/", wishlist_view, name = "wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name = "add-to-wishlist"),
    path("delete-from-wishlist/", delete_item_from_wishlist, name ="delete-from-wishlist"),

    path('make-offer/<pid>/', make_offer, name='make-offer'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view,name= "sign-up"),
    path("login/", views.login_view, name= "login"),
    path("logout/", views.logout_view, name = "logout"),
]

home/forms.py
from django import forms
from home.models import ProductReview, ArtistReview, UserReview, UserRating, Contact, NewsletterSubscriber, Profile, Offer
from cities_light.models import Country, City

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write a review"}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']


class ArtistReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write a review"}))

    class Meta:
        model = ArtistReview
        fields = ['review', 'rating']

class UserReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Write a testimonial"}))

    class Meta:
        model = UserReview
        fields = ['review']

class UserRatingForm(forms.ModelForm):
    class Meta:
        model = UserRating
        fields = ['rating']


class CheckoutForm(forms.Form):
    country = forms.ModelChoiceField(queryset=Country.objects.all(), empty_label="Select a country")
    city = forms.ModelChoiceField(queryset=City.objects.all(), empty_label="Select a city")

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'phone', 'subject', 'message']

class NewsletterSubscriptionForm(forms.ModelForm):
    class Meta:
        model = NewsletterSubscriber
        fields = ['email']

class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder" : "First name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder" : "Last name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder" : "Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder" : "Phone number (You don't have to specify which region)"}))
    
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'image', 'bio', 'phone']


class OfferForm(forms.ModelForm):
    offer_price = forms.DecimalField(max_digits=10, decimal_places=2, widget=forms.NumberInput(attrs={'placeholder':"Your custom price"}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder':"Tell the artist about your offer"}))
    class Meta:
        model = Offer
        fields = ['offer_price', 'message']

home/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.http import JsonResponse
from django.db.models import Q, Avg, Count, F
from home.models import Technique, Style, SubjectMatter, Philosophy, Product, Artist, ProductReview, ArtistReview, CartOrder, CartOrderItems, Address, WishList, UserReview, UserRating, Profile, Offer
from home.forms import ProductReviewForm, ArtistReviewForm, CheckoutForm, UserReviewForm, UserRatingForm, ContactForm, NewsletterSubscriptionForm, ProfileForm, OfferForm
from django.template.loader import render_to_string

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from paypal.standard.forms import PayPalPaymentsForm

from django.contrib.auth.decorators import login_required

from django.contrib import messages

import calendar, stripe
from django.db.models.functions import ExtractMonth

from django.core.exceptions import ObjectDoesNotExist

import datetime, json

def index(request):
    artists = Artist.objects.all()
    products = Product.objects.all()
    
    try:
        chosen_product = Product.objects.get(chosen=True)
        exclusive_products = Product.objects.filter(exclusive = True)
        featured_products = Product.objects.filter(featured = True)
    except ObjectDoesNotExist:
        chosen_product = None
        exclusive_products = None
        featured_products = None

    # Add user reviews / ratings :

    reviews = UserReview.objects.all().order_by("-date") # to show the latest reviews
    ratings = UserRating.objects.all().order_by("-date")

    

    
    user_rating = UserRating()
    user_review = UserReview()

    if request.method == 'POST':
        if request.POST.get('action') == 'review': 
            user_review = UserReview.objects.create(
            user=request.user,
            review=request.POST['review']
        )
        elif request.POST.get('action') == 'rating':  
            user_rating = UserRating.objects.create(
            user=request.user,
            rating=request.POST['rating']
        )

    # User review form
    review_form = UserReviewForm()
    rating_form = UserRatingForm()
    
    # Allow only 1 review per user
    make_review = True
    make_rating = True
    
    rating_count = UserRating.objects.all().count()
    
    if request.user.is_authenticated:
        user_review_count = UserReview.objects.filter(user=request.user).count()
        user_rating_count = UserRating.objects.filter(user=request.user).count()

        if user_review_count > 0:
            make_review = False
        if user_rating_count > 0:
            make_rating = False
    

    average_rating = UserRating.objects.all().aggregate(rating=Avg("rating"))

    if request.user.is_authenticated:
        user = request.user # to get the current user
        context = {
        'featured_products':featured_products,
        'exclusive_products':exclusive_products,
        'chosen_product':chosen_product,
        'products':products,
        'artists':artists,

        'user':user.username,
        'review':user_review.review,
        'reviews':reviews,
        'ratings':ratings,
        'review_form':review_form,
        'rating_form':rating_form,
        'make_review':make_review,
        'make_rating':make_rating,
        'rating':user_rating.rating,
        "average_rating":average_rating,
        'rating_count':rating_count,
    }
    else:
        context = {
        'featured_products':featured_products,
        'exclusive_products':exclusive_products,
        'chosen_product':chosen_product,
        'products':products,
        'artists':artists,

        'review':user_review.review,
        'reviews':reviews,
        'ratings':ratings,
        'review_form':review_form,
        'rating_form':rating_form,
        # 'make_review':make_review,
        'rating':user_rating.rating,
        "average_rating":average_rating,
        'rating_count':rating_count,
    }
    return render(request,'home/index.html', context)

def services_view(request):

    return render(request, 'home/services.html')

def contact_view(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request,"Message sent! Thank you for your feedback.")
            return redirect("home:contact")
    else:
        contact_form = ContactForm()
    

    # Handling the subscription to NewsLetter
    if request.method == 'POST':
        newsletter_form = NewsletterSubscriptionForm(request.POST)
        if newsletter_form.is_valid():
            newsletter_form.save()
            messages.success(request,"Subscribed!")
            return redirect("home:contact")
    else:
        newsletter_form = NewsletterSubscriptionForm()

    context = {
        'contact_form':contact_form,
        'newsletter_form':newsletter_form,
    } 
    return render(request,'home/contact.html', context)


def about_view(request):
    reviews = UserReview.objects.all().order_by("-date")

    context = {
        'reviews':reviews,
    }
    
    return render(request,'home/about.html', context)

def faqs_view(request):
    
    return render(request,'home/faqs.html')

def product_list_view(request):
    products = Product.objects.filter(product_status = "published")
    techniques = Technique.objects.all().order_by('title')
    styles = Style.objects.all().order_by('title')
    subjects = SubjectMatter.objects.all().order_by('title')
    philosophies = Philosophy.objects.all().order_by('title')
    
    context = {
        "products":products,
        "techniques":techniques,
        "styles":styles,
        "subjects":subjects,
        "philosophies":philosophies,
    }
    return render(request,'store/store.html', context)


def product_detail_view(request, pid):
    
    current_url = request.build_absolute_uri()
    next_url = request.GET.get('next')

    product = Product.objects.get(pid=pid)
    product_wishlist_count = product.wishlist_set.count()
    product_images = product.product_images.all()
    related_products = Product.objects.filter(Q(technique=product.technique) | Q(style=product.style)).exclude(pid=pid)[:10]

    # Reviews 
    reviews = ProductReview.objects.filter(product=product).order_by("-date") # to show the latest reviews

    # Get average reviews of a product
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating = Avg('rating'))

    # Product review form
    review_form = ProductReviewForm()

    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()
        
        if user_review_count > 0:
            make_review = False

    # Check if the logged-in user is the artist themselves
    if request.user == product.artist.user:
        make_review = False
       


    context = {
        "product":product,
        "product_images":product_images,
        "reviews":reviews,
        "review_form":review_form,
        "average_rating":average_rating,
        "related_products":related_products,
        "make_review":make_review,
        "next_url": next_url,
        "current_url":current_url,
        'product_wishlist_count':product_wishlist_count,
    }
    return render(request, "store/product-details.html",context)


def artist_list_view(request):
    artists = Artist.objects.all()
    techniques = Technique.objects.all().order_by('title')
    styles = Style.objects.all().order_by('title')
    subjects = SubjectMatter.objects.all().order_by('title')
    philosophies = Philosophy.objects.all().order_by('title')
    context = {
        "artists": artists,
        "techniques":techniques,
        "styles":styles,
        "subjects":subjects,
        "philosophies":philosophies,
    }
    return render(request, "artists/artists.html",context)

def artist_detail_view(request, aid):
    current_url = request.build_absolute_uri()
    next_url = request.GET.get('next')

    print("next url",next_url)
    print("current url ", current_url)


    artist = Artist.objects.get(aid=aid)
    reviews = ArtistReview.objects.filter(artist=artist).order_by("-date") # to show the latest reviews

    # Get average reviews of a product
    average_rating = ArtistReview.objects.filter(artist=artist).aggregate(rating = Avg('rating'))

    # Increment artist view count
    artist.views += 1
    artist.save()

    # Product review form
    review_form = ArtistReviewForm()
    
    # Allow only 1 review per artist per user
    make_review = True
    if request.user.is_authenticated:
        user_review_count = ArtistReview.objects.filter(user=request.user, artist=artist).count()

        if request.user == artist.user:
            make_review = False
            
        elif user_review_count > 0:
            make_review = False
    
    context = {
        "artist": artist,
        "reviews":reviews,
        "make_review":make_review,
        "review_form":review_form,
        "average_rating":average_rating,
        "next_url": next_url,
        "current_url":current_url,
    }
    return render(request, "artists/artist-details.html",context)


def add_product_review(request,pid):
    product = Product.objects.get(pk=pid)
    user = request.user # to get the logged in user
    review = ProductReview.objects.create(
        user = user,
        product = product,
        review = request.POST['review'],
        rating = request.POST['rating']
    )

    product_images = product.product_images.all()
    related_products = Product.objects.filter(Q(technique=product.technique) | Q(style=product.style)).exclude(pid=pid)[:10]

    # Reviews 
    reviews = ProductReview.objects.filter(product=product).order_by("-date") # to show the latest reviews

    # Get average reviews of a product

templates/home/index.html
{% extends 'partials/base.html' %}

{% load static %} 

{% block title %} Home {% endblock title %}

{% block cssFilename %} /static/homestyle.css {% endblock cssFilename %}

{% block script %} /static/homejs.js {% endblock script %}

{% block header %}
&nbsp;
{% endblock header %}
{% block content %}
<header id="header-0">
    <div>
        <h1>Artful Atlas</h1>
        <h2>Welcome to Artful Atlas - your gateway to a world of Moroccan art and culture. Explore our diverse collection and experience the beauty of Moroccan artworks.</h2>
        <h2 id="down00">Explore</h2>
    </div>
    <img src="{% static 'images/paintings/elderly-riad.png' %}" alt="">
</header>

{% if chosen_product %}
<a href="{% url 'home:product-details' chosen_product.pid %}">
    <header id="selection" class="first-header">
        <!-- <h1 id="first-h1">Stare at her enough...</h1> -->
        <!-- <img id="first" src="{% static 'images/images-testing/1most-beautiful.png' %}" alt="Image of a young lady"> -->
        <!-- <h1 id="second-h1">And it starts to look Alive </h1> -->
        <h1 id="third-h1">Selection of the month</h1>
        <h1 id="fourth-h1">-{{chosen_product.artist}}</h1>
        <img style="display:none;" id="down0" src="{% static 'images/arrows/down.png' %}" alt="Scroll-Down">
</header>
</a>
{% endif %}
<!-- We added this script because we want to handle the artwork of the month manually, but I have it as a css property, not an image tag, so I found a workaround -->
<script>
    var imageUrl = "{{chosen_product.image.url}}";
    var selection = document.getElementById("selection");
    if (selection) {
        selection.style.backgroundImage = "url(" + imageUrl + ")";
    }
</script>

<header id="nav" class="sticky">
    <nav class="flexboxcontainer">
        <a class="flexbox" href="{% url 'home:index' %}"><h1 style="color:rgba(0,0,0,0.7);text-shadow:none; font-size:50px;">Artful Atlas</h1></a>
        <a class="flexbox" href="{% url 'home:index' %}">Home</a>
        <a class="flexbox" href="{% url 'home:services' %}">Services</a>
        <a class="flexbox" href="{% url 'home:contact' %}">Contact</a>
        <a class="flexbox" href="{% url 'home:about' %}">About</a>
        <a class="flexbox" href="{% url 'home:artists' %}">Artists</a>
        <a class="flexbox" href="{% url 'home:store' %}">Store</a>
        <div class="flexbox dropdown">
            <a href="{% if request.user.is_authenticated %}{% url 'home:dashboard' %}{% else %}{% url 'userauths:login' %}{% endif %}">Account</a>
            <div class="dropdown-content">
                {% if request.user.is_authenticated %}
                {% if request.user.user_type == 'artist' %}
                        <a href="{% url 'artist-dashboard:artist-dashboard' %}">Artist Dashboard</a>
                {% endif %}
                    <a href="{% url 'home:dashboard' %}">Dashboard</a>
                    <a href="{% url 'home:dashboard' %}">Profile</a>
                    <a href="{% url 'userauths:logout' %}">Log out</a>
                {% else %}
                    <a href="{% url 'userauths:login' %}">Login</a>
                    <a href="{% url 'userauths:sign-up' %}">Sign up</a>
                {% endif %}
            </div>
        </div>

        <div class="flexbox">
            <a class="cart" href="{% url 'home:cart' %}">
                <img class="icons" src="{% static 'images/icons/cart.png' %}" alt="cart icon" width="25" height="25">
                <span id="cart-counter">{{request.session.cart_data_object|length}}</span>
            </a>
        </div>
        <div class="flexbox">
            <a class="cart" href="{% url 'home:wishlist' %}">
                <img class="icons" src="{% static 'images/icons/heart.png' %}" alt="cart icon" width="25" height="25">
                <span id="wishlist-counter">{{wishlist_count}}</span>
            </a>
        </div>
    </nav>
</header>

{% if exclusive_products %}
<header id="intro1">
    <br><br>
    <h1 title="Unique artworks (no copies)">Exclusive Artworks</h1>
    <figure>
        {% for p in exclusive_products %}
            {% if forloop.counter0 == 0 %}
                <a href="{% url 'home:product-details' p.pid %}"><img id="intro2" class="animate-trigger" src="{{p.image.url}}" alt=""></a>
            {% endif %}
        {% endfor %}
      <span class="larger">Dive deeper into the world of art collecting with our <a href="store2.html">limited edition Exclusive Artworks</a>. Explore the depths of creativity and discover the perfect piece to elevate your space.</span>
        {% for p in exclusive_products %}
            {% if forloop.counter0 == 1 %}
                <a href="{% url 'home:product-details' p.pid %}"><img id="intro3" class="animate-trigger" src="{{p.image.url}}" alt=""></a>
            {% endif %}
            {% if forloop.counter0 == 2 %}
                <a href="{% url 'home:product-details' p.pid %}"><img id="intro4" class="animate-trigger" src="{{p.image.url}}" alt=""></a>
            {% endif %}
        {% endfor %}
    </figure>
</header>
{% endif %}

<!-- <header id="explore">
    <h1>And so, we leave you to explore our <span style="color:lightskyblue">Artful Atlas!</span></h1>
</header> -->
{% if featured_products %}
<header id="featured-products">
    <br><br>
    <h1 title="Popular artworks">Featured Artworks</h1>
    <span class="larger">Enjoy our collection of standout <a href="store2.html">Featured Products</a>, each chosen for its exceptional quality and artistic merit. These handpicked pieces offer a touch of elegance for any space. Find your next statement artwork and elevate your surroundings with timeless beauty.</span>
    <section class="flex0">
        {% for p in featured_products %}
        <div>
            <a class="larger" style="text-decoration:underline;" href="{% url 'home:artist-details' p.artist.aid %}">{{p.artist}}</a>
            <a href="{% url 'home:product-details' p.pid %}"><img class="featured-product" src="{{p.image.url}}" alt="Artwork"></a>
        </div>
        {% endfor %}
    </section>
    <br><br><br><br><br><br>
</header>
{% endif %}

<header class="flex">
    <header id="slider1" class="slider">
        <h1>Our Artists</h1>
        <div class="slider-images">
            {% for p in products %}
            <a href="{% url 'home:artist-details' p.artist.aid %}">
                <img class="slider-image" src="{{p.artist.image.url}}" alt="Image 2">
            {% endfor %}
            </a>
        </div>
        <!-- <div class="slider-arrows">
            <img class="slider-arrow left-arrow" src="{% static '/images/arrows/left.png' %}" alt="Previous">
            <img class="slider-arrow right-arrow" src="{% static '/images/arrows/right.png' %}" alt="Next">
        </div> -->
    </header> 
    
    <header id="slider2" class="slider">
        <h1>Their touch</h1>
        <div class="slider-images">
            {% for p in products %}
            <a href="{% url 'home:product-details' p.pid %}">
                <img class="slider2-image" src="{{p.image.url}}">
            </a>
            {% endfor %}                    
        </div>
        <!-- <div class="slider-arrows">
            <img class="slider-arrow left-arrow" src="{% static '/images/arrows/left.png' %}" alt="Previous">
            <img class="slider-arrow right-arrow" src="{% static '/images/arrows/right.png' %}" alt="Next">
        </div> -->
    </header>
</header>

<header id="discover-artists">
    <span class="larger">Discover a curated collection of captivating artworks by Moroccan talented artists. From mesmerizing paintings to exquisite landscapes, explore diverse expressions of creativity that inspire and enrich. Dive into our artists' corner and find the perfect piece to elevate your space.</span>
    <h1 id="h1-artists">More about our  <a href="{% url 'home:artists' %}">artists</a></h1>
</header>

<br><br><br><br>

<h1>Testimonials!</h1>
<section id="reviews">
    {% if not reviews %}
    <br>
    <span class="larger">No testimonials yet.</span>
    <br>
    {% else %}
        {% for r in reviews %}
        <div class="flex" id="review">
            <img id="user-profile-picture" src="{% static 'images/sign-up/customer.jpg' %}" alt="">
            <h3>{{r.user.username|title}}</h3> <br>
            <p>{{r.date|date:"F d, Y"}}</p> <br>
        </div>
        <p style="text-align:start;"> - {{r.review}}</p> <br>
    {% endfor %}
    {% endif %}
    
    {% if make_review == True %}
    {% if request.user.is_authenticated %}
    <div id="hide">
        <h3>Add a testimonial</h3>
        <form action="{% url 'home:index' %}" id="addReview" method="post">
            {% csrf_token %}
            <p>{{review_form.review}}</p>
            <input type="hidden" name="action" value="review">
            <button class="button" id="submit" type="submit">Submit</button>
        </form>
    </div>
    {% endif %}
    {% endif %}
    <br><br>
    <p id="review-message"></p>
    {% if not request.user.is_authenticated %}
        <p>You must be logged in to be able to post a comment or a review. 
            <a href="{% url 'userauths:login' %}?next={{ current_url }}">Log in</a>
        </p>
        <br>
        <p>Don't have an account yet? <a href="{% url 'userauths:sign-up' %}">Sign up</a></p>
    {% endif %}
</section>

<br><br><br>

<h1>Customer Ratings</h1>
<section id="ratings">
    {% if not ratings %}
    <br>
    <span class="larger">No ratings yet.</span>
    <br>
    {% else %}
        {% if rating_count == 1  %} 
        <p>1 User rating.</p>
        {% else  %}
        <p>{{rating_count}} Users ratings</p>
        {% endif %}

        <br>
        <h2>Current Score : {{average_rating.rating|floatformat}}/5</h2>
    {% endif %}

    {% if make_rating == True %}
    {% if request.user.is_authenticated %}
    <div>
    <h3>Rate us!</h3>
        <form action="{% url 'home:index' %}" id="addReview" method="post">
            {% csrf_token %}
            <p>{{rating_form.rating}}</p>
            <input type="hidden" name="action" value="rating">
            <button class="button" id="submit" type="submit">Submit</button>
        </form>
    </div>
    {% endif %}
    {% endif %}
    <p id="review-message"></p>
    <br><br>
    {% if not request.user.is_authenticated %}
        <p>You must be logged in to be able to post a comment or a review. 
            <a href="{% url 'userauths:login' %}?next={{ current_url }}">Log in</a>
        </p>
        <br>
        <p>Don't have an account yet? <a href="{% url 'userauths:sign-up' %}">Sign up</a></p>
    {% endif %}
</section>
<br><br><br>
{% endblock content %}

templates/home/wishlist.html
{% extends 'partials/base.html' %}

{% load static %}

{% block title %} Wishlist {% endblock title %}

{% block cssFilename %} /static/wishliststyle.css {% endblock cssFilename %}


{% block content %}
<header id="added-artworks">
    <h1>Wishlist</h1>
    {% if wishlist %}
        {% for w in wishlist %}
    <section class="flex" id="wishlist-artworks" style="margin-bottom:3%;">
        <figure>
            <a href="{% url 'home:product-details' w.product.pid %}"><img class="artwork-image" src="{{w.product.image.url}}" alt="">
            <figcaption style="margin-bottom:5%;" class="artwork-title">{{w.product.title}}</figcaption>
            </a>
        </figure>

        <div>
            <h2>Artist</h2>
            <h3><a class="artwork-artist" href="{% url 'home:artist-details' w.product.artist.aid %}">{{w.product.artist}}</a></h3>
        </div>
        <div>
            <h2>Price</h2> 
            <h3 class="price" style="text-align:center;">{{w.product.price}}</h3>
        </div>
        <div>
            <h2 class="flex">Availability</h2> 
            <h3>{% if w.product.available %}
                Available
                {% else %}
                Sold
                {% endif %}
            </h3>
        </div>
        <span>
            <input type="hidden" class="product-id" value="{{w.product.id}}" name="" id="">
        </span>
        <input type="hidden" class="product-title" value="{{w.product.title}}" name="" id="">
        <input type="hidden" id="product_page">
        <a style="display:none;" data-product-url="{% url 'home:product-details' w.product.pid %}" href="{% url 'home:product-details' w.product.pid %}">
                    </a>
        <p class="cart-button">Add To Cart</p>
        <p class="delete"><img style="width:40px;height:40px;" src="{% static 'images/icons/x-mark.png' %}" alt=""></p>
        <hr>
        <br><br><br>
    </section>
    
    {% endfor %}

    <br><br><br><br>
    <!-- Used a different class so that "Item added!" message won't show up if this button is clicked -->
    <p class="go-to-cart">
        <a href="{% url 'home:cart' %}" class="cart-button-redirecter" id="go-to-cart">Go to Cart</a>
    </p>
    <br>
    {% else %}
        <div id="else-h2">
            <h2 >There are no artworks in your wishlist yet.</h2>
            <br><br>
        </div>
    {% endif %}

{% endblock content %}