artist_dashboard/urls.py
from django.urls import path, include

from artist_dashboard.views import artist_dashboard, update_profile, artworks, edit_artwork, orders, reviews, account_details, delete_artwork, order_detail, offers, offer_detail

app_name = "artist-dashboard"


urlpatterns = [
    path("", artist_dashboard, name="artist-dashboard"),
    path("update-profile/<aid>/", update_profile, name= "update-profile"),
    path("artworks/", artworks, name="artworks"),
    path("edit-artwork/<pid>/", edit_artwork, name="edit-artwork"),
    path("delete-artwork/<pid>/", delete_artwork, name = "delete-artwork"),
    path("orders/", orders, name="orders"),
    path("orders/order-details/<id>", order_detail, name = "order-details"),
    path("reviews/", reviews, name="reviews"),
    path("account-details/", account_details, name="account-details"),
    path("offers/", offers, name="offers"),
    path("offers/offer-details/<id>", offer_detail, name = "offer-details"),

]

atlas/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path("user/",include("userauths.urls")),
    path("artist-dashboard/", include("artist_dashboard.urls")),

    # google authentication and whatnot
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home.views import index, product_list_view, artist_list_view, artist_detail_view, product_detail_view, add_product_review, add_artist_review, artist_search_view, product_search_view, add_to_cart, cart_view, delete_item_from_cart, payment, payment_completed_view, payment_failed_view, customer_dashboard, order_details, update_address_status, delete_address, wishlist_view, add_to_wishlist, delete_item_from_wishlist, services_view, contact_view, about_view, faqs_view, checkout, update_order, make_offer

app_name = "home"

urlpatterns = [
    path("",index, name="index"),
    path("services/", services_view, name = "services"),
    path("contact/", contact_view, name = "contact"),
    path("about/", about_view, name = "about"),
    path("faqs/", faqs_view, name = "faqs"),

    path("store/",product_list_view, name="store"),
    path("store/<pid>/",product_detail_view, name="product-details"),

    path("artists/", artist_list_view, name = "artists"),
    path("artists/<aid>/",artist_detail_view, name="artist-details"),

    path("add-product-review/<int:pid>/",add_product_review, name ="add-product-review"),
    path("add-artist-review/<int:aid>/",add_artist_review, name ="add-artist-review"),

    path("search/artists/", artist_search_view, name = "artist-search"),
    path("search/artworks/", product_search_view, name= "product-search"),

    path("add-to-cart/", add_to_cart, name = "add-to-cart"),
    path("cart/",cart_view, name="cart"),
    path("delete-from-cart/",delete_item_from_cart, name="delete-from-cart"),

    path("payment/<oid>/", payment, name ="payment"),

    path("checkout/", checkout, name = "checkout"),

    path("paypal/", include('paypal.standard.ipn.urls')), 
    path("payment/payment-completed/<oid>/", payment_completed_view, name = "payment-completed"),
    path("payment/payment-failed/", payment_failed_view, name = "payment-failed"),
    path("update-order/", update_order, name = "update_order"),

    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_details, name="order-details"),
    path("update-address-status/", update_address_status, name = "update-address-status"),
    path("delete-address/", delete_address, name = "delete-address"),

    path("wishlist/", wishlist_view, name = "wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name = "add-to-wishlist"),
    path("delete-from-wishlist/", delete_item_from_wishlist, name ="delete-from-wishlist"),

    path('make-offer/<pid>/', make_offer, name='make-offer'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view,name= "sign-up"),
    path("login/", views.login_view, name= "login"),
    path("logout/", views.logout_view, name = "logout"),
]

templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'messagesstyle.css' %}">
    <link rel="stylesheet" href="{% static 'sharedstyle.css' %}">
    <link rel="icon" href="/static/images/logos-images/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="{% block cssFilename %} {% endblock cssFilename %}">  <!--To include the specific style file-->
    {% block moreCssFiles %} {% endblock moreCssFiles %}
    <script defer src="{% block script %}{% endblock script %}"></script>
    <script src="{% static 'messagesjs.js' %}" defer></script>
    <script src="{% static 'cart.js' %}" defer></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'wishlistjs.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js" defer></script>
    <title>{% block title %} {% endblock title %} </title>
</head>
<body>
    <script style="z-index:9999999999999999999999999999999999999999999999;" defer type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="95191b3b-415c-4bb3-8572-f5123e99dfbf";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
    <div id="message-container">Item added!</div>

    <!-- Handling the login / sign-up / etc messages -->
    {% if messages %}
        <div id="messages">
            {% for message in messages %}
                <div class="message" data-tags="{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

{% block header %}
    <header id="nav" class="sticky">
        <nav class="flexboxcontainer">
            <a class="flexbox" href="{% url 'home:index' %}"><span style="color:rgba(0,0,0,0.7);text-shadow:none; font-size:50px;">Artful Atlas</span></a>
            <a class="flexbox" href="{% url 'home:index' %}">Home</a>
            <a class="flexbox" href="{% url 'home:services' %}">Services</a>
            <a class="flexbox" href="{% url 'home:contact' %}">Contact</a>
            <a class="flexbox" href="{% url 'home:about' %}">About</a>
            <a class="flexbox" href="{% url 'home:artists' %}">Artists</a>
            <a class="flexbox" href="{% url 'home:store' %}">Store</a>
            <div class="flexbox dropdown">
                <a href="{% if request.user.is_authenticated %}{% url 'home:dashboard' %}{% else %}{% url 'userauths:login' %}{% endif %}">Account</a>
                <div class="dropdown-content">
                    {% if request.user.is_authenticated %}
                    {% if request.user.user_type == 'artist' %}
                            <a href="{% url 'artist-dashboard:artist-dashboard' %}">Artist Dashboard</a>
                    {% endif %}
                        <a href="{% url 'home:dashboard' %}">Dashboard</a>
                        <a href="{% url 'home:dashboard' %}">Profile</a>
                        <a href="{% url 'userauths:logout' %}">Log out</a>
                    {% else %}
                        <a href="{% url 'userauths:login' %}">Login</a>
                        <a href="{% url 'userauths:sign-up' %}">Sign up</a>
                    {% endif %}
                </div>
            </div>
                        
            <div class="flexbox">
                <a class="cart" href="{% url 'home:cart' %}">
                    <img class="icons" src="{% static 'images/icons/cart.png' %}" alt="cart icon" width="25" height="25">
                    <span id="cart-counter">{{request.session.cart_data_object|length}}</span>
                </a>
            </div>
            <div class="flexbox">
                <a class="cart" href="{% url 'home:wishlist' %}">
                    <img class="icons" src="{% static 'images/icons/heart.png' %}" alt="cart icon" width="25" height="25">
                    <span id="wishlist-counter">{{wishlist_count}}</span>
                </a>
            </div>
        </nav>
    </header>

{% endblock header %}

    <main>
        {% block content %}

        {% endblock content %}
    </main>

    <footer class="footer2">
        <div class="parent">
            <div class="div1">
                <h3 class="gridbox">How may we help you?</h3>
                <p><a href="{% url 'home:faqs' %}">FAQS</a></p>
                <br>
                <p><a href="{% url 'home:contact' %}">Contact us</a></p> 
            </div>

            <div class="div2"> 
                <h3>Learn more</h3>
                <p>Learn more <a href="{% url 'home:about' %}">about us</a></p>
                <br>
                <p>Learn more about our <a href="{% url 'home:artists' %}">artists</a></p>
            </div>

            <div class="div3">
                <h3>Customer services</h3>
                <p>Discover our <a href="{% url 'home:services' %}">services</a></p>
            </div>
        <div class="div4">
            <h3>Shop now</h3>
            <p>Visit our <a href="{% url 'home:store' %}">store</a></p>
        </div>
        <!-- <div class="div5">
            <h3>language</h3>
                <p>English - <a href="">Change</a></p>
        </div> -->
    </div>
        <br>
        <br>
        <p>Copyright &copy; 2024 Artful Atlas. All rights reserved</p>
        <hr>
        <a href="{% url 'home:index' %}"><img class="logo" src="{% static 'images/logos-images/logo.png' %}" alt="Artful Atlas Logo"></a>
    </footer>
    
</body>
</html>