atlas/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path("user/",include("userauths.urls")),
    path("artist-dashboard/", include("artist_dashboard.urls")),

    # google authentication and whatnot
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home.views import index, product_list_view, artist_list_view, artist_detail_view, product_detail_view, add_product_review, add_artist_review, artist_search_view, product_search_view, add_to_cart, cart_view, delete_item_from_cart, payment, payment_completed_view, payment_failed_view, customer_dashboard, order_details, update_address_status, delete_address, wishlist_view, add_to_wishlist, delete_item_from_wishlist, services_view, contact_view, about_view, faqs_view, checkout, update_order, make_offer

app_name = "home"

urlpatterns = [
    path("",index, name="index"),
    path("services/", services_view, name = "services"),
    path("contact/", contact_view, name = "contact"),
    path("about/", about_view, name = "about"),
    path("faqs/", faqs_view, name = "faqs"),

    path("store/",product_list_view, name="store"),
    path("store/<pid>/",product_detail_view, name="product-details"),

    path("artists/", artist_list_view, name = "artists"),
    path("artists/<aid>/",artist_detail_view, name="artist-details"),

    path("add-product-review/<int:pid>/",add_product_review, name ="add-product-review"),
    path("add-artist-review/<int:aid>/",add_artist_review, name ="add-artist-review"),

    path("search/artists/", artist_search_view, name = "artist-search"),
    path("search/artworks/", product_search_view, name= "product-search"),

    path("add-to-cart/", add_to_cart, name = "add-to-cart"),
    path("cart/",cart_view, name="cart"),
    path("delete-from-cart/",delete_item_from_cart, name="delete-from-cart"),

    path("payment/<oid>/", payment, name ="payment"),

    path("checkout/", checkout, name = "checkout"),

    path("paypal/", include('paypal.standard.ipn.urls')), 
    path("payment/payment-completed/<oid>/", payment_completed_view, name = "payment-completed"),
    path("payment/payment-failed/", payment_failed_view, name = "payment-failed"),
    path("update-order/", update_order, name = "update_order"),

    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_details, name="order-details"),
    path("update-address-status/", update_address_status, name = "update-address-status"),
    path("delete-address/", delete_address, name = "delete-address"),

    path("wishlist/", wishlist_view, name = "wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name = "add-to-wishlist"),
    path("delete-from-wishlist/", delete_item_from_wishlist, name ="delete-from-wishlist"),

    path('make-offer/<pid>/', make_offer, name='make-offer'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view,name= "sign-up"),
    path("login/", views.login_view, name= "login"),
    path("logout/", views.logout_view, name = "logout"),
]

templates/store/product-details.html
{% extends 'partials/base.html' %}

{% load static %}

{% block title %} Artwork's details {% endblock title %}

{% block cssFilename %} /static/product-details-style.css {% endblock cssFilename %}

{% block script %} /static/product-details-js.js {% endblock script %}

{% block content %}
    <header id="artwork-overview" class="flex">
        <section id="artwork-images-container">
            <img id="artwork-image" src="{{ product.image.url }}" alt="">
            <div>
                <img class="secondary-images" src="{{ product.image.url }}" alt="">
                {% for p in product_images %}
                    <img class="secondary-images" src="{{ p.images.url }}" alt="">
                {% endfor %}
            </div>
        </section>
        
        <section id="info">
            <div class="info-sections">
                <h1>Title : {{product.title}}</h1>
                <br>
            </div>

            <div class="info-sections">
            <h1>Details :</h1>
                <br>
                <ul id="artwork-info" class="flex">
                    <div id="first-list">
                        <li>Artist : <a id="artist-name" href="{% url 'home:artist-details' product.artist.aid %}">{{product.artist.name}}</a></li>
                        <li>Execution date : {{product.date|date:"F d, Y"}}</li>
                        <li>Availability : <strong>{% if product.available %} Available {% else %} SOLD {% endif %}</strong></li>
                        <li>Reference : {{ product.pid|slice:"7:" }}</li>
                    </div>
                    <div>
                        {% if not product.medium == other %}
                        <li>Medium :  {{product.medium}}</li>
                        {% endif %}
                        <li>Dimensions : {{product.width}} W x {{product.height}} H x {{product.depth}} D cm</li>
                        <li>Technique : {{product.technique}}</li>
                        <li>Style : {{product.style}}</li> 
                    </div>
                </ul>
            </div>

            <br>
            {% if product.available == True %}
            <div class="info-sections" id="price-section">
                <h1>Price and Shipping</h1>
                <br>
                <h3 style="display:inline-block;margin-bottom:10px;" class="price">{{product.price}}</h3> <span>dh</span>
                <br>
                <p>Shipping : {{product.shipping|title}}</p>
                <br>
            </div>
            <div class="cart-div">
                <input type="hidden" class="product-id" value="{{product.id}}" name="" id="">
                <input type="hidden" class="product-title" value="{{product.title}}" name="" id="">
                <!-- <input type="number" value="1" name="" id="product-quantity"> -->
                <button class="button cart-button" id="cart-button" type="submit">
                    <img class="icons" src="{% static 'images/icons/white-cart.png' %}" alt="">
                    <input type="hidden" id="product_page">
                    <a style="display:none;" data-product-url="{% url 'home:product-details' product.pid %}" href="{% url 'home:product-details' product.pid %}">
                    </a>
                    <span>Add to Cart</span>
                </button>
            </div>

            <a style="text-decoration:none;" href="{% url 'home:make-offer' product.pid %}">
                <div class="button offer"> 
                    <img class="icons" src="{% static 'images/icons/bid.png' %}" alt="">
                    <span>Make an Offer!</span>
                </div>
            </a>

            <div class="button wishlist add-to-wishlist" data-product-item="{{product.id}}"> 
                <img class="icons" src="{% static 'images/icons/heart.png' %}" alt="">
                <span>Add to Wishlist</span>
            </div>
            {% endif %}
        </section>
    </header>
    <br><br>
    <header>
        <h1>Artworks's specifications</h1>
        <br>
        <p style="padding:2%;">{% if product.specifications %}
            {{product.specifications}} 
            {% else %}
            No specifications provided by the artist yet. 
            {% endif %}
        </p>
    </header>
    <br><br>
    <header>
        <h1>Artwork's description according to the artist</h1>
        <br>
        
        <p style="padding:2%;">
            {% if product.description %}
            {{product.description}}
            {% else %}
            No description is provided by the artist yet.
            {% endif %}
        </p>
    </header>
    

    <header id="extra" class="flex">
        <div class="extra-info">
            <img class="icons" src="{% static 'images/icons/signature.png' %}" alt="Signature"> <br>
            {% if signed_by_artist %}
            <p>Artwork signed by the Artist</p>
            {% else %}
            <p>Artwork Not signed by the Artist</p>
            {% endif %}
        </div>
        <div class="extra-info">
            <img class="icons" src="{% static 'images/icons/favorite.png' %}" alt="Wishlist box"> <br>
            {% if product_wishlist_count > 0 %}
            <p>This artwork is part of {{product_wishlist_count}} wishlists</p>
            {% else %}
            <p>This artwork is not part of any wishlist just yet</p>
            {% endif %}
        </div>
        <div class="extra-info">
            <img class="icons" src="{% static 'images/icons/happiness.png' %}" alt="Happiness!"> <br>
            <p>10-day return policy</p>
        </div>
        <div class="extra-info">
            <img class="icons" src="{% static 'images/icons/box.png' %}" alt="Shipping"> <br>
            <p>Shipping across the world</p>
        </div>
        <div class="extra-info"><img class="icons" src="{% static 'images/icons/credit-card.png' %}" alt="Secure transaction"> <br>
            <p>100% secure transaction</p>
        </div>
        <div class="extra-info">
            <img style="width:50px;height:50px;" src="{% static 'images/icons/returns.png' %}" alt="Returns"> <br>
            <p>Free Returns</p>
        </div>
    </header>

    <header>
        <h1>Comments & reviews</h1> <br>
        <section id="reviews">
            {% if not reviews %}
                <br>
                <p>No reviews or comments yet.</p>
                <br>
            {% else %}
            <p style="text-align:end">Average rating : {{average_rating.rating|floatformat}}  /5</p>
            {% for r in reviews %}
                <div class="flex" id="review">
                    <img id="user-profile-picture" src="{% static 'images/sign-up/customer.jpg' %}" alt="">
                    <h3>{{r.user.username|title}}</h3> <br>
                    <h3>{{r.get_rating_display}}</h3>
                    <p>{{r.date|date:"F d, Y"}}</p> <br>
                </div>
                <p> - {{r.review}}</p> <br>
            {% endfor %}
            {% endif %}

            {% if make_review == True %}
            {% if request.user.is_authenticated %}
            <div id="hide">
            <h3>Add a review</h3>
                <form action="{% url 'home:add-product-review' product.id %}" id="addReview" method="post">
                    {% csrf_token %}
                    <p>{{review_form.review}}</p>
                    <p>{{review_form.rating}}</p>
                    <button class="button" id="submit" type="submit">Submit</button>
                </form>
            </div>
            {% endif %}
            {% endif %}
            <p id="review-message"></p>
            <br>
            {% if not request.user.is_authenticated %}
                <p>You must be logged in to be able to post a comment or a review. 
                    <a href="{% url 'userauths:login' %}?next={{ current_url }}">Log in</a>
                </p>
                <br>
                <p>Don't have an account yet? <a href="{% url 'userauths:sign-up' %}?next={{ current_url }}">Sign up</a></p>
            {% endif %}
        </section>
        <br>
        <h1>About the author</h1> <br>
        <section id="profile">
            <div class="profile-info">
                <figure>
                    <img class="profile-pictures" src="{{product.artist.image.url}}" alt="Profile picture">
                    <figcaption><a href="{% url 'home:artist-details' product.artist.aid %}">View profile</a></figcaption>
                </figure>
                &nbsp;
                <a id="artist-name" href="{% url 'home:artist-details' product.artist.aid %}">{{product.artist.name}}</a>
                &nbsp;&nbsp;
                <p>{{product.artist.views}}</p> &nbsp;
                <img class="icons" src="{% static 'images/icons/eye.png' %}" alt="Eye Icon">
                &nbsp;&nbsp;
                <p>{{product.artist.city}}</p> &nbsp;
                <img class="icons" src="{% static 'images/icons/location.png' %}" alt="Location Icon">
                &nbsp;&nbsp;
                <p>Short Bio : {{product.artist.shortBio}}</p>
            </div>
            <h2>Biography</h2> <br>
            <p>{{product.artist.biography}}</p>
            <br>
        </section>

        <br>

        <section>
        {% if related_products %}
            <h1>Discover more artworks of the same technique & style</h1> <br>  
        {% endif %}
        <header class="store">
            {% for product in related_products %}
                <figure>
                    <a data-product-url="{% url 'home:product-details' product.pid %}" href="{% url 'home:product-details' product.pid %}">
                        {% if product.image %}
                            <img class="store-images" src="{{ product.image.url }}" alt="{{ product.title }}">
                        {% endif %}
                    </a>
                    <a data-product-url="{% url 'home:product-details' product.pid %}" href="{% url 'home:product-details' product.pid %}" target="_blank" ><p class="view-more">View More</p></a>
                    <p>{{ product.title }}</p>
                    <p class="price">{{ product.price }}</p> <span>dh</span>
                    <p> By <a id="artist-name" href="{% url 'home:artist-details' product.artist.aid %}">{{product.artist}}</a> </p>
                    <input type="hidden" class="product-id" value="{{product.id}}" name="" id="">
                    <input type="hidden" class="product-title" value="{{product.title}}" name="" id="">
                    <p class="cart-button">Add To Cart</p>
                    <br>
                    <p class="add-to-wishlist wish-button" data-product-item="{{product.id}}">Add to Wishlist</p>
                </figure>
            {% endfor %}
        </header>
        <br>
    </header>
{% endblock content %}

templates/store/store.html
{% extends 'partials/base.html' %}

{% load static %} 

{% block title %} Gallery {% endblock title %}

{% block cssFilename %} /static/storestyle.css {% endblock cssFilename %}

{% block script %} /static/storejs.js {% endblock script %}

{% block content %}

<h1>Featured Artworks</h1>
<header class="store">
    {% for product in products %}
        {% if product.featured == True and product.product_status == "published" %}
        <figure>
            <a data-product-url="{% url 'home:product-details' product.pid %}" href="{% url 'home:product-details' product.pid %}">
                {% if product.image %}
                    <img class="store-images" src="{{ product.image.url }}" alt="{{ product.title }}">
                {% endif %}
            </a>
            <a data-product-url="{% url 'home:product-details' product.pid %}" href="{% url 'home:product-details' product.pid %}" target="_blank" ><p class="view-more">View More</p></a>
            <p>{{ product.title }}</p>
            <p class="price">{{ product.price }}</p> <span>dh</span>
            <p> By <a id="artist-name" href="{% url 'home:artist-details' product.artist.aid %}">{{product.artist}}</a> </p>
            <input type="hidden" class="product-id" value="{{product.id}}" name="" id="">
            <input type="hidden" class="product-title" value="{{product.title}}" name="" id="">
            {% if product.available == True %}
            <p class="cart-button">Add To Cart</p>
            <br>
            <p class="add-to-wishlist wish-button" data-product-item="{{product.id}}">Add to Wishlist</p>
            {% endif %}
        </figure>
        {% endif %}
    {% endfor %}
</header>

<header id="filter">
    <form action="{% url 'home:product-search' %}" method="GET">
        <h1 id="filter-header"> <img class="icons" src="{% static 'images/icons/filter.png' %}" alt=""> Search for an Artwork </h1> 
        <button id="search" type="submit"><img class="icons" src="{% static 'images/icons/search.png' %}" alt=""></button>
        <section id="drop-content" class="hidden"> 
            <div>
                <p>Title</p>
                <input type="text" placeholder ="Artwork's title.." name="q">
            </div>   
            
            <div>
                <p>Techniques used</p>
                <ul>
                    {% for t in techniques %}
                    <li class="filter-item" data-category="techniques" data-id="{{ t.id }}">{{ t.title }}</li>
                    <input type="checkbox" class="checkbox-hidden" name="techniques" value="{{ t.id }}">
                    {% endfor %}
                </ul>
            </div>
            
            <div>
                <p>Styles used</p>
                <ul>
                    {% for s in styles %}
                    <li class="filter-item" data-category="styles" data-id="{{ s.id }}">{{ s.title }}</li>
                    <input type="checkbox" class="checkbox-hidden" name="styles" value="{{ s.id }}">
                    {% endfor %}
                </ul>
            </div>
            
            <div>
                <p>Subject Matter</p>
                <ul>
                    {% for s in subjects %}
                    <li class="filter-item" data-category="subjects" data-id="{{ s.id }}">{{ s.title }}</li>
                    <input type="checkbox" class="checkbox-hidden" name="subjects" value="{{ s.id }}">
                    {% endfor %}
                </ul>
            </div>
            
            <div>
                <p>Artistic philosophy</p>
                <ul>
                    {% for p in philosophies %}
                    <li class="filter-item" data-category="philosophies" data-id="{{ p.id }}">{{ p.title }}</li>
                    <input type="checkbox" class="checkbox-hidden" name="philosophies" value="{{ p.id }}">
                    {% endfor %}
                </ul>
            </div>

            <div>
                <p>Price Range</p>
                <ul>
                    <li class="filter-item" data-category="price_range" data-id="under_500">Under 500</li>
                    <input type="checkbox" class="checkbox-hidden" name="price_range" value="under_500">
            
                    <li class="filter-item" data-category="price_range" data-id="500_1000">500-1000</li>
                    <input type="checkbox" class="checkbox-hidden" name="price_range" value="500_1000">
            
                    <li class="filter-item" data-category="price_range" data-id="1000_2000">1000-2000</li>
                    <input type="checkbox" class="checkbox-hidden" name="price_range" value="1000_2000">

                    <li class="filter-item" data-category="price_range" data-id="2000_5000">2000-5000</li>
                    <input type="checkbox" class="checkbox-hidden" name="price_range" value="2000_5000">

                    <li class="filter-item" data-category="price_range" data-id="5000_10000">5000-10000</li>
                    <input type="checkbox" class="checkbox-hidden" name="price_range" value="5000_10000">
            
                    <li class="filter-item" data-category="price_range" data-id="above_10000">Above 10000</li>
                    <input type="checkbox" class="checkbox-hidden" name="price_range" value="above_10000">
                </ul>
            </div>
            
            
            
            </div>
        </section>
    </form>
</header>

<h1>Artworks</h1>

<header class="store">
    {% for product in products %}
        {% if product.featured == False and product.product_status == "published" %}
        <figure>
            <a data-product-url="{% url 'home:product-details' product.pid %}" href="{% url 'home:product-details' product.pid %}">
                {% if product.image %}
                    <img class="store-images" src="{{ product.image.url }}" alt="{{ product.title }}">
                {% endif %}
            </a>
            <a data-product-url="{% url 'home:product-details' product.pid %}" href="{% url 'home:product-details' product.pid %}" target="_blank" ><p class="view-more">View More</p></a>
            <p>{{ product.title }}</p>
            <p class="price">{{ product.price }}</p> <span>dh</span>
            <p> By <a id="artist-name" href="{% url 'home:artist-details' product.artist.aid %}">{{product.artist}}</a> </p>
            <input type="hidden" class="product-id" value="{{product.id}}" name="" id="">
            <input type="hidden" class="product-title" value="{{product.title}}" name="" id="">
            {% if product.available == True %}
            <p class="cart-button">Add To Cart</p>
            <br>
            <p class="add-to-wishlist wish-button" data-product-item="{{product.id}}">Add to Wishlist</p>
            {% endif %}
        </figure>
        {% endif %}
    {% endfor %}
</header>
 
{% endblock content %}