artist_dashboard/urls.py
from django.urls import path, include

from artist_dashboard.views import artist_dashboard, update_profile, artworks, edit_artwork, orders, reviews, account_details, delete_artwork, order_detail, offers, offer_detail

app_name = "artist-dashboard"


urlpatterns = [
    path("", artist_dashboard, name="artist-dashboard"),
    path("update-profile/<aid>/", update_profile, name= "update-profile"),
    path("artworks/", artworks, name="artworks"),
    path("edit-artwork/<pid>/", edit_artwork, name="edit-artwork"),
    path("delete-artwork/<pid>/", delete_artwork, name = "delete-artwork"),
    path("orders/", orders, name="orders"),
    path("orders/order-details/<id>", order_detail, name = "order-details"),
    path("reviews/", reviews, name="reviews"),
    path("account-details/", account_details, name="account-details"),
    path("offers/", offers, name="offers"),
    path("offers/offer-details/<id>", offer_detail, name = "offer-details"),

]

atlas/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls")),
    path("user/",include("userauths.urls")),
    path("artist-dashboard/", include("artist_dashboard.urls")),

    # google authentication and whatnot
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home.views import index, product_list_view, artist_list_view, artist_detail_view, product_detail_view, add_product_review, add_artist_review, artist_search_view, product_search_view, add_to_cart, cart_view, delete_item_from_cart, payment, payment_completed_view, payment_failed_view, customer_dashboard, order_details, update_address_status, delete_address, wishlist_view, add_to_wishlist, delete_item_from_wishlist, services_view, contact_view, about_view, faqs_view, checkout, update_order, make_offer

app_name = "home"

urlpatterns = [
    path("",index, name="index"),
    path("services/", services_view, name = "services"),
    path("contact/", contact_view, name = "contact"),
    path("about/", about_view, name = "about"),
    path("faqs/", faqs_view, name = "faqs"),

    path("store/",product_list_view, name="store"),
    path("store/<pid>/",product_detail_view, name="product-details"),

    path("artists/", artist_list_view, name = "artists"),
    path("artists/<aid>/",artist_detail_view, name="artist-details"),

    path("add-product-review/<int:pid>/",add_product_review, name ="add-product-review"),
    path("add-artist-review/<int:aid>/",add_artist_review, name ="add-artist-review"),

    path("search/artists/", artist_search_view, name = "artist-search"),
    path("search/artworks/", product_search_view, name= "product-search"),

    path("add-to-cart/", add_to_cart, name = "add-to-cart"),
    path("cart/",cart_view, name="cart"),
    path("delete-from-cart/",delete_item_from_cart, name="delete-from-cart"),

    path("payment/<oid>/", payment, name ="payment"),

    path("checkout/", checkout, name = "checkout"),

    path("paypal/", include('paypal.standard.ipn.urls')), 
    path("payment/payment-completed/<oid>/", payment_completed_view, name = "payment-completed"),
    path("payment/payment-failed/", payment_failed_view, name = "payment-failed"),
    path("update-order/", update_order, name = "update_order"),

    path("dashboard/", customer_dashboard, name="dashboard"),
    path("dashboard/order/<int:id>", order_details, name="order-details"),
    path("update-address-status/", update_address_status, name = "update-address-status"),
    path("delete-address/", delete_address, name = "delete-address"),

    path("wishlist/", wishlist_view, name = "wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name = "add-to-wishlist"),
    path("delete-from-wishlist/", delete_item_from_wishlist, name ="delete-from-wishlist"),

    path('make-offer/<pid>/', make_offer, name='make-offer'),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view,name= "sign-up"),
    path("login/", views.login_view, name= "login"),
    path("logout/", views.logout_view, name = "logout"),
]

artist_dashboard/models.py
from django.db import models

# Create your models here.

artist_dashboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden
from django.db.models import Sum, Count
from home.models import CartOrder, Product, Technique, Style, Philosophy, SubjectMatter, CartOrderItems, Artist, ProductReview, ArtistReview, Offer
from .forms import addArtworkForm, UpdateOrderStatusForm, ProfileImageForm, CoverImageForm, SocialMediaForm, ArtistInfoForm, OrientationForm, DescriptionForm,BiographyForm, UpdateOfferStatusForm

import datetime
from django.contrib import messages
from django.contrib.auth.hashers import check_password


def artist_dashboard(request):
    user = request.user

    try:
        # Retrieve data for the artist dashboard
        artist = Artist.objects.get(user=user)
        
        # Retrieve the number of orders involving the artist, through the artworks chosen by the buyer
        total_orders_count = CartOrder.objects.filter(cartorderitems__product__artist=artist).count()       

        # Revenue from orders involving the artist's artworks
        revenue = CartOrder.objects.filter(cartorderitems__product__artist=artist, paid_status=True).aggregate(total_revenue=Sum('price'))['total_revenue'] or 0

        # Artworks created by the artist
        artworks_number = Product.objects.filter(artist=artist).count()

        this_month = datetime.datetime.now().month

        monthly_revenue = CartOrder.objects.filter(cartorderitems__product__artist=artist, paid_status=True, order_date__month=this_month).aggregate(total_revenue=Sum('price'))['total_revenue'] or 0
    
    except Artist.DoesNotExist:
        # If the user is not an artist, return a forbidden response
        return HttpResponseForbidden("You are not authorized yet to access this page as you are not an artist. Please go to your Account details in your account dashboard and become an artist.")

    context = {
        'artist': artist,
        'total_orders_count': total_orders_count,
        'revenue': revenue,
        'artworks_number': artworks_number,
        'this_month':this_month,
        'monthly_revenue':monthly_revenue,
    }

    return render(request, "artist-dashboard/dashboard.html", context)

def artworks(request):
    user = request.user 
    artist = Artist.objects.get(user=user)

    # Add Artwork
    form = addArtworkForm()
    if request.method == "POST" and "add-artwork-button-name" in request.POST:
        form = addArtworkForm(request.POST, request.FILES)
        if form.is_valid():
            new_form = form.save(commit = False)
            new_form.user = user
            new_form.artist = artist 
            new_form.save() 
            form.save_m2m() # many 2 many field
            form = addArtworkForm()


    # Artworks created by the artist
    artworks = Product.objects.filter(artist=artist).order_by("-id")

    context = {
        'artist':artist,
        'artworks':artworks,
        'form':form,
    }
    return render(request, "artist-dashboard/artworks.html", context)


def edit_artwork(request, pid):
    user = request.user 
    artist = Artist.objects.get(user=user)

    artworks = Product.objects.filter(artist=artist).order_by("-id")
    artwork = Product.objects.get(pid = pid)

    # Edit Artwork
    form = addArtworkForm(instance = artwork)
    if request.method == "POST":
        form = addArtworkForm(request.POST, request.FILES, instance = artwork)
        if form.is_valid():
            new_form = form.save(commit = False)
            new_form.user = user
            new_form.artist = artist 
            new_form.save() 
            form.save_m2m() # many 2 many field
            return redirect("artist-dashboard:artworks")

    context = {
        'artist':artist,
        'artworks':artworks,
        'form':form,
    }

    return render(request, "artist-dashboard/edit-artwork.html", context)

def delete_artwork(request, pid):
    artwork = Product.objects.get(pid = pid)
    artwork.delete()
    return redirect("artist-dashboard:artworks")



def orders(request):
    user = request.user 
    artist = Artist.objects.get(user=user)
    
    # Same thing for orders associated with the artist
    orders = CartOrder.objects.filter(cartorderitems__product__artist=artist)

    context = {
        'artist':artist,
        'orders':orders,
        
    }
    return render(request, "artist-dashboard/orders.html", context)

def order_detail(request, id):
    order = CartOrder.objects.get(id = id)
    order_items = CartOrderItems.objects.filter(order = order)
    user = request.user 
    artist = Artist.objects.get(user=user)

    if request.method == 'POST':
        form = UpdateOrderStatusForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            messages.success(request, "Order status has been updated successfully.")
            return redirect('artist-dashboard:orders')
    else:
        form = UpdateOrderStatusForm()

    context = {
        'artist':artist,
        'order':order,
        'order_items':order_items,
        'form':form,
    }

    return render(request, "artist-dashboard/order-details.html", context)


def reviews(request):
    user = request.user 
    artist = Artist.objects.get(user=user)

    product_reviews = ProductReview.objects.filter(product__in = artist.product.all())
    artist_reviews = ArtistReview.objects.filter(artist = artist)


    context = {
        'artist':artist,
        'product_reviews':product_reviews,
        'artist_reviews':artist_reviews,
        
    }
    return render(request, "artist-dashboard/reviews.html", context)



def update_profile(request, aid):
    artist = Artist.objects.get(aid=aid)
    reviews = ArtistReview.objects.filter(artist=artist).order_by("-date")


    cover_image_form = CoverImageForm(instance=artist)
    profile_image_form = ProfileImageForm(instance=artist)
    social_media_form = SocialMediaForm(instance=artist)
    artist_info_form = ArtistInfoForm(instance=artist)
    biography_form = BiographyForm(instance=artist)
    description_form = DescriptionForm(instance=artist)
    orientation_form = OrientationForm(instance=artist)
    
    if request.method == 'POST':
            
        if 'cover-photo-name' in request.POST:
            cover_image_form = CoverImageForm(request.POST, request.FILES, instance=artist)
            if cover_image_form.is_valid():
                cover_image_form.save()
                messages.success(request, "Your cover photo has been successfully modified!")
                return redirect('home:artist-details', artist.aid)
        
        elif 'profile-image-name' in request.POST:
            profile_image_form = ProfileImageForm(request.POST, request.FILES, instance=artist)
            if profile_image_form.is_valid():
                profile_image_form.save()
                messages.success(request, "Your profile photo has been successfully modified!")
                return redirect('home:artist-details', artist.aid)

        elif 'social-media-name' in request.POST:
            social_media_form = SocialMediaForm(request.POST, instance=artist)
            if social_media_form.is_valid():
                social_media_form.save()
                messages.success(request, "Your social media links have been successfully modified!")
                return redirect('home:artist-details', artist.aid)
        
        elif 'artist-info-name' in request.POST:
            artist_info_form = ArtistInfoForm(request.POST, instance=artist)
            if artist_info_form.is_valid():
                artist_info_form.save()
                messages.success(request, "Your information have been successfully modified!")
                return redirect('home:artist-details', artist.aid)
        
        elif 'biography-name' in request.POST:
            biography_form = BiographyForm(request.POST, instance=artist)
            if biography_form.is_valid():
                biography_form.save()
                messages.success(request, "Your biography has been successfully modified!")
                return redirect('home:artist-details', artist.aid)

        elif 'description-name' in request.POST:
            description_form = DescriptionForm(request.POST, instance=artist)
            if description_form.is_valid():
                description_form.save()
                messages.success(request, "Your description has successfully modified!")
                return redirect('home:artist-details', artist.aid)
            
        elif 'orientation-name' in request.POST:
            orientation_form = OrientationForm(request.POST, instance=artist)
            if orientation_form.is_valid():
                orientation_form.save()
                messages.success(request, "Your orientation has been successfully modified!")
                return redirect('home:artist-details', artist.aid)
        

    context = {
        'artist': artist,
        'profile_image_form': profile_image_form,
        'cover_image_form': cover_image_form,
        'social_media_form': social_media_form,
        'artist_info_form': artist_info_form,
        'orientation_form': orientation_form,
        'description_form': description_form,
        'biography_form': biography_form,
        'reviews': reviews,
    }

    return render(request, 'artist-dashboard/update-profile.html', context)



def account_details(request):
    user = request.user 
    artist = Artist.objects.get(user=user)


    if request.method == "POST":
        if 'info-name' in request.POST:
            artist.name = request.POST.get("name")
            artist.email = request.POST.get("email")
            user.email = request.POST.get("email")
            artist.address = request.POST.get("address")
            artist.phone = request.POST.get("phone")
            artist.save()
            messages.success(request, "Information updated successfully.")
            return redirect("artist-dashboard:account-details")

templates/artist-dashboard/partials/base.html
{% load static %}
<section id="secondary-nav">
    <a href="{% url 'artist-dashboard:artist-dashboard' %}">
        <div class="flex tab" id="overview-tab" style="background-color:lightblue;">
            <img class="icons" src="{% static 'images/icons/overview.png' %}" alt="">
            <span>Overview</span>
        </div>
    </a>

    <a href="{% url 'artist-dashboard:update-profile' artist.aid %}">
        <div class="flex" id="edit-profile-tab">
            <img class="icons" src="{% static 'images/icons/edit.png' %}" alt=""> 
            <span>View & Edit Profile</span>
        </div>
    </a>

    <a href="{% url 'artist-dashboard:artworks' %}">
        <div class="flex tab" id="artworks-tab">
            <img class="icons" src="{% static 'images/icons/artwork.png' %}" alt=""> 
            <span>Artworks</span>
        </div>
    </a>
    <a href="{% url 'artist-dashboard:orders' %}">
        <div class="flex tab"  id="orders-tab">
            <img class="icons" src="{% static 'images/icons/orders.png' %}" alt=""> 
            <span>Orders</span>
        </div>
    </a>

    <a href="{% url 'artist-dashboard:offers' %}">
        <div class="flex tab"  id="offers-tab">
            <img class="icons" src="{% static 'images/icons/bid.png' %}" alt=""> 
            <span>Offers</span>
        </div>
    </a>

    <a href="{% url 'artist-dashboard:reviews' %}">
        <div class="flex tab" id="reviews-tab">
            <img class="icons" src="{% static 'images/icons/review.png' %}" alt=""> 
            <span>Reviews</span>
        </div>
    </a>
    
    <a href="{% url 'artist-dashboard:account-details' %}">
        <div class="flex tab" id="account-details-tab">
            <img class="icons" src="{% static 'images/icons/account.png' %}" alt=""> 
            <span>Account details</span>
        </div>
    </a>
    <a href="{% url 'userauths:logout' %}">
        <div class="flex">
            <img class="icons" src="{% static 'images/icons/logout.png' %}" alt=""> 
            <span>Logout</span>
        </div>
    </a>
</section>

templates/artist-dashboard/partials/header.html
{% load static %}
<header id="nav" class="sticky">
    <nav class="flexboxcontainer">
        <a class="flexbox" href="{% url 'home:index' %}"><span style="color:rgba(0,0,0,0.7);text-shadow:none; font-size:50px;">Artful Atlas</span></a>
        <a class="flexbox" href="{% url 'home:index' %}">Home</a>
        <a class="flexbox" href="{% url 'home:services' %}">Services</a>
        <a class="flexbox" href="{% url 'home:contact' %}">Contact</a>
        <a class="flexbox" href="{% url 'home:about' %}">About</a>
        <a class="flexbox" href="{% url 'home:artists' %}">Artists</a>
        <div class="flexbox dropdown">
            <a href="{% if request.user.is_authenticated %}{% url 'home:dashboard' %}{% else %}{% url 'userauths:login' %}{% endif %}">Account</a>
            <div class="dropdown-content">
                {% if request.user.is_authenticated %}
                {% if request.user.user_type == 'artist' %}
                        <a href="{% url 'artist-dashboard:artist-dashboard' %}">Artist Dashboard</a>
                {% endif %}
                    <a href="{% url 'home:dashboard' %}">Dashboard</a>
                    <a href="{% url 'home:dashboard' %}">Profile</a>
                    <a href="{% url 'userauths:logout' %}">Log out</a>
                {% else %}
                    <a href="{% url 'userauths:login' %}">Login</a>
                    <a href="{% url 'userauths:sign-up' %}">Sign up</a>
                {% endif %}
            </div>
        </div>
        <a class="flexbox" href="{% url 'home:store' %}">Store</a>
    </nav>
</header>